couchdb:
  https: no
  ip_address: 115.146.93.148
  port: "5984"
  login: admin
  password: password
  databases:
    tweets: tweets
    users: users
twitter:
  OAuth:
    consumer_key: SokfKsh8QWsDgcKUadn2sIxUK
    consumer_secret: ZeNk54222XlPuemXOoLHJzItpLoXiZDJNMR9aaSCuiu8iLMOhW
    access_token: 1106931541-fKClHIwPfncj9WY3wSw6oQWcL9wO6EffUebhtqA
    access_secret: 7dGlUYG5SNreV8IvFLC4Aq7OLRXHKJwC3vLltMNboSFdv
